default_install_hook_types: [pre-commit, pre-push, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: local
    hooks:
      # formatting
      - id: prettier
        name: prettier
        entry: prettier --write --ignore-unknown
        language: node
        exclude: "target/.*|.git/.*"
        additional_dependencies: ["prettier"]
      # public builds
      - id: tsc
        name: tsc
        entry: tsc
        language: node
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies: ["typescript", "@types/tampermonkey@5.0.3"]
  - repo: "https://github.com/jorisroovers/gitlint"
    rev: "v0.19.1"
    hooks: [{ id: gitlint }]
